apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: rishma18121998/flask-app:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"  # Minimum memory allocated
            cpu: "250m"      # Minimum CPU allocated
          limits:
            memory: "256Mi"  # Maximum memory allowed
            cpu: "500m"      # Maximum CPU allowed
