name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t rishma18121998/flask-app:latest ./app
        docker push rishma18121998/flask-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y curl conntrack socat

    - name: Install kubectl
      run: |
        sudo snap install kubectl --classic

    - name: Set up Minikube as a non-root user
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        sudo useradd -m dockeruser
        sudo usermod -aG docker dockeruser
        sudo chown -R dockeruser:dockeruser /home/dockeruser
        sudo su - dockeruser -c "minikube start --driver=docker"

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f $GITHUB_WORKSPACE/k8s/deployment.yaml
        kubectl apply -f $GITHUB_WORKSPACE/k8s/service.yaml

